### PR TITLE
added a "rollback" task which can be included using

### PR DESCRIPTION
**Pull request by haarcuba**
a deploy:rollback task

### CODE REVIEW

**Comment by haarcuba** [comment]
removed awk dependence

**Comment by chauncey-garrett** [comment]
@haarcuba Sweet! Now hopefully it'll get merged.

For posterity, https://github.com/cabara/mina/commit/dcd65957e1d63f0442d0fe8334761a9da2b89120#commitcomment-10061706

**Comment by d4be4st** [comment]
I liked #9 @tmandry solution better. sorry

**Comment by chauncey-garrett** [comment]
@d4be4st Looks even better! Glad to have this one. Now to get it on a release ;)

**Comment by d4be4st** [comment]
Mina 0.3.3 released with rollback feature

**Pull request closed without merging**
