### PR TITLE
Allow for a build step

### PR DESCRIPTION
**Pull request by dchancogne**
Add a ':build' step that can be executed after the deployment has been
done and the code moved to its final destination but before the sysmlink
for the current release has been updated (aka new code is live).
This allows for build steps that require code to be in its final
destination (i.e. some autoloaders resolve full paths, moving the code
after the autoloader has done its setup work breaks the code).

### CODE REVIEW

**Comment by d4be4st** [comment]
I am not sure this extra step is really needed. You can always use $release_path in to :launch do block to get use the release path for your autoloaders

``` ruby
to :launch do
  queue "echo #{deploy_to}/$release_path"
end
```

**Comment by dchancogne** [comment]
@d4be4st The issue is not with getting the value for the actual path. 
During the launch block the new version of the app is already running (i.e. the symlink has been updated). Any actual build process (like running CSS thru a preprocessor, concatenating JS ...etc.) would them mean downtime for the application.
These builds steps need to happen before the new version of the app is made live, i.e. in/during the build process. But since the build process is done in a temp directory it causes anything that precompute or cache absolute path to get an invalid path.

**Comment by dchancogne** [comment]
@d4be4st Any update on this? Any change you can merge this?

**Comment by d4be4st** [comment]
Not true. It might be that current path is pointing to the newest path but you still did not restart your application, and that means the old code is still running on your application. 

But i will merge this as it seems like a good idea.

**Pull request merged**
