### PR TITLE
deploy on multiple hosts

### PR DESCRIPTION
**Pull request by haarcuba**
deploy on multiple machines: added the "hosts" configuration variable, which can be specified instead
of "domain". The "hosts" variable should be set to a list, e.g.

set :hosts, [ "server1.com", "server2.com" ]

### CODE REVIEW

**Comment by huobazi** [comment]
cool~

**Comment by lidashuang** [comment]
:+1:

**Comment by haarcuba** [comment]
actually this is less than ideal, since it doesn't work in parallel.
I'll do that in the future if this one gets merged.

**Comment by d4be4st** [comment]
@haarcuba could you maybe do this as a separate module? Most of mina users use only one server, and we were hoping to not bloat mina, as it is easy to make separate gems for these situations.

**Pull request closed without merging**
