### PR TITLE
Implemented text file upload to the server and rendering of templates.

### PR DESCRIPTION
**Pull request by dariocravero**
Hi all,

A common case scenario while deploying an app is to create configuration files on the fly such as a database config file.

I don't know how you're currently handling this and given the nature of how a Mina script runs you can't use scp (unless something like a reverse tunnel is created or something like [zssh's zr command](http://zssh.sourceforge.net/) is used).

On the current patch I'm using [*read*](http://serverfault.com/questions/72476/clean-way-to-write-complex-multi-line-string-to-a-variable) to read text files/content and echo them on the server to a file.

There're two methods:
* *put*, which allows random content to be uploaded to a file, and
* *render*, which renders a template and uploads it to the file (defaults to erb but anything can be used).

Perhaps, if there's a need to upload binary files scp could be used and a parallel connection open?

What do you think? Is this useful?
Thanks,
Darío

### CODE REVIEW

**Comment by jerefrer** [comment]
Any news on this ?

**Comment by jerefrer** [comment]
Another solution would be to use https://github.com/adie/mina-scp.

Here's how I quickly made a `template` method using `scp_upload`:

    desc "writes the .env file"
    task :write_env_file do
      template '.env', 'current/.env'
    end

    private

    def template(from, to)
      queue %{ echo "-----> Rendering template file #{from} to #{to}" }
      template_path = File.expand_path("config/deploy/templates/#{from}.erb")
      temp_file_path = "/tmp/#{from}.#{application}"
      File.open(temp_file_path, 'w') do |f|
        f.puts erb(template_path)
      end
      scp_upload(temp_file_path, "#{deploy_to}/#{to}")
    end

To be used with a template file inside `config/deploy/templates/template_file.erb`

**Comment by d4be4st** [comment]
you can use :before_hook and :after_hook for this

**Comment by Frexuz** [comment]
`mina/scp` doesn't work with mina 1.x. So here's just my solution if anyone needs it :)

```
# extending mina with helpers, require this file in deploy.rb
module Mina
  module Helpers
    module Internal
      def write_config(config_template, file)
        command "echo '#{config_template}' | sudo tee #{file}" # better than "echo 'hello' >> file"
      end

      def template(path)
        erb("#{fetch(:template_path)}/#{path}")
      end
    end
  end
end
```

in any task:
```
namespace :provision do
  task :redis
    # install etc here
    upstart_config = template('upstart/redis-server.conf')
    write_config(upstart_config, '/etc/init/redis-server.conf')
  end
end
```

**Pull request closed without merging**
